services:
  - type: web
    name: nestjs-api
    env: node
    plan: free
    buildCommand: yarn install && npx prisma generate && yarn build
    startCommand: |
      npx prisma db push
      node dist/main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nestjs-db
          property: connectionString

databases:
  - name: nestjs-db
    plan: free